### ISSUE TITLE
Homepage is not responsive

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/infragram#94]
[Demo](https://streamable.com/8qkae)

User has to zoom in/out and scroll in order to see what the site is about.
Let's not forget that more than 50% of global traffic is from smartphones.

A responsive website is mandatory, not optional anymore :)

**Comment by jywarren** [comment]
This is great, however we are making that page static so it has to work from a saved HTML copy of that page. This repository is for just the contents of https://infragram.org/sandbox but we can still manage this issue here. Thanks!

I want to open another one that may be more challenging - making the https://infragram.org/sandbox interface responsive too!

**Comment by VladimirMikulic** [comment]
Alright, thanks.

**Comment by jywarren** [comment]
Aha! Already exists! https://github.com/publiclab/infragram/issues/7
